"""updated Property model

Revision ID: 52856b757f87
Revises: f8f4128c7b35
Create Date: 2023-07-19 08:10:16.821736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52856b757f87'
down_revision = 'f8f4128c7b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
